import { SupportedCountry } from "./Types";

export const SUPPORTED_COUNTRIES: SupportedCountry[] = [
	{name:"Nigeria",
		country: "NG",
		currency: "NGN",
		flag: "🇳🇬",
		ticker: "₦",
		countryCode: "+234",
		cashback: "1500",
	},
	{name:"Ghana",
		country: "GH",
		currency: "GHS",
		flag: "🇬🇭",
		ticker: "₵",
		countryCode: "+233",
		cashback: "15",
	},
	{name:"Kenya",
		country: "KE",
		currency: "KES",
		flag: "🇰🇪",
		ticker: "KSh",
		countryCode: "+254",
		cashback: "150",
	},
	{name:"South Africa",
		country: "ZA",
		currency: "ZAR",
		flag: "🇿🇦",
		ticker: "R",
		countryCode: "+27",
		cashback: "19",
	},
	{name:"Uganda",
		country: "UG",
		currency: "UGX",
		flag: "🇺🇬",
		ticker: "USh",
		countryCode: "+256",
		cashback: "3700",
	},
];

export const defaultCountry= {name:"Nigeria",
    country: "NG",
    currency: "NGN",
    flag: "🇳🇬",
    ticker: "₦",
    countryCode: "+234",
    cashback: "1500",
}
